### ISSUE TITLE
Encryptation security issue

### ISSUE THREAD

**Issue by amadeusgray** [Brian3647/Pandia#14]
He encontrado algunas cosas raras, como por ejemplo, la contraseña va a través de un plain text hasta el request de la base de datos, donde en la API ya lo convierten en un hash, el problema es que esa contraseña alguien puede interceptar en plain text en el request, lo cual estaría comprometiendo la contraseña del usuario. Por cierto, me parece genial que intentes encriptarlo! :)

**Comment by Brian3647** [comment]
> He encontrado algunas cosas raras, como por ejemplo, la contraseña va a través de un plain text hasta el request de la base de datos, donde en la API ya lo convierten en un hash, el problema es que esa contraseña alguien puede interceptar en plain text en el request, lo cual estaría comprometiendo la contraseña del usuario. Por cierto, me parece genial que intentes encriptarlo! :)

Tienes razón, pero, ¿Cómo podría hacer el hash desde el lado del cliente cuando necesito una librería a la que solo puedo acceder desde el servidor?

**Comment by Brian3647** [comment]
@amadeusgray Si puede ser, explica alguna manera de solucionar esto, si no, intentaré hacerlo yo mañana con lo que pueda

**Comment by amadeusgray** [comment]
Realmente, no necesitas para nada el bcrypt en el backend, puedes hacer lo siguiente:

El password es pasada a hash con un salt en el frontend.
La password es enviada al backend. (En este punto en donde estaba ese problema de seguridad)
El backend compara el hash que ha sido enviado desde el frontend con el que está guardado en la base de datos, no hace falta convertirlo a plain text.
Antes de compararlo debes asegurarte que se parezca a un hash, por ejemplo usando regex.
Si son iguales los 2 hashes simplemente manda un 200 OK, si no un error.

Listo, eso sería, es dificil explicarlo bien aqui, por eso si necesitas más ayuda para hacer esto no dudes en contactarme en discord. amadeusgray#4709

**Comment by Brian3647** [comment]
@amadeusgray https://security.stackexchange.com/questions/93395/how-to-do-client-side-hashing-of-password-using-bcrypt
